name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:9.4.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: "8.4.12-fpm"
            coverage: xdebug

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            nc -z localhost 3306 && break
            sleep 1
          done

      - name: Codeception Unit tests
        run: vendor/bin/codecept run Unit

      - name: Codeception Functional tests
        run: vendor/bin/codecept run Functional
